import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";
import prettier from "eslint-config-prettier/flat";

const eslintConfig = defineConfig([
  globalIgnores([
    ".next/**",
    "out/**",
    "build/**",
    "coverage/**",
    "playwright-report/**",
    "test-results/**",
    "next-env.d.ts",
    // Generated by `npm run db:types`; formatting/shape is Supabase's concern.
    "src/types/database.generated.ts",
  ]),
  ...nextVitals,
  ...nextTs,
  {
    rules: {
      // Type safety is a stated project constraint (see docs/DEVELOPMENT.md).
      // `any` is allowed only at documented boundaries via an explicit disable.
      "@typescript-eslint/no-explicit-any": "error",
      "@typescript-eslint/consistent-type-imports": [
        "error",
        { prefer: "type-imports", fixStyle: "inline-type-imports" },
      ],
      "@typescript-eslint/no-unused-vars": [
        "error",
        { argsIgnorePattern: "^_", varsIgnorePattern: "^_", caughtErrorsIgnorePattern: "^_" },
      ],
      // Content and curriculum live in the database, not in component code.
      "no-restricted-syntax": [
        "error",
        {
          selector: "TSEnumDeclaration",
          message:
            "Use a union type or a database enum instead of a TypeScript enum (see docs/DEVELOPMENT.md).",
        },
      ],
    },
  },
  {
    // Node-side tooling and scripts.
    files: ["*.config.{js,mjs,ts}", "scripts/**/*.{js,mjs,ts}"],
    rules: {
      "@typescript-eslint/no-require-imports": "off",
    },
  },
  // Must stay last: turns off stylistic rules that conflict with Prettier.
  prettier,
]);

export default eslintConfig;
